# SPDX-License-Identifier: MIT
#
# Spacemacs for Helix, see https://github.com/langston-barrett/spacelix

# TODO: Spacebones dark!
theme = "onedark"

# A few notes on what follows:
#
# - When a command is bound to a key, the default Helix keybinding is removed
#   (by setting the key to "no_op").
# - Keybindings are organized first by mode, then parent key, then
#   alphabetically.
# - Keybindings that match between Helix and Spacemacs are still explicitly
#   bound in case the Helix defaults change, but are marked `# default` for
#   clarity. (There are more to be done, however!)
# - Section names are inspire by the Spacemacs documentation.

# ---------------------------------------------------------
# Normal

[keys.normal]
"C-c" = "no_op"  # default: toggle_comments, instead: SPC ;
";" = "toggle_comments"
"@" = "replay_macro"
"$" = "goto_line_end"
"*" = ["search_selection", "search_next"]
"0" = "goto_line_start"
"V" = ["select_mode", "extend_to_line_bounds"]
"D" = ["exit_select_mode", "select_mode", "goto_line_end", "delete_selection"]
"G" = "goto_last_line"
"q" = "record_macro"
"C-r" = "redo"
"H" = "goto_window_top"
"L" = "goto_window_bottom"

# Executing commands
[keys.normal.space]
"space" = "command_palette"
"o" = "no_op"  # reserved for user in Spacemacs

# Buffer manipulation
[keys.normal.space.b]
"b" = "buffer_picker"
"d" = ":buffer-close"
"n" = "goto_next_buffer"
"p" = "goto_previous_buffer"
"s" = ":new"
"Y" = ["select_all", "yank"]

# Error handling
[keys.normal.space.e]
"l" = "workspace_diagnostics_picker"
"n" = "goto_next_diag"
"p" = "goto_prev_diag"

# File manipulation
[keys.normal.space.f]
"f" = "file_picker"
"s" = ":write"

[keys.normal.space.f.e]
"d" = ":config-open"
"R" = ":config-reload"

[keys.normal.g]
"l" = "no_op"  # default: goto_line_end, instead: $
"n" = "no_op"  # default: goto_next_buffer, instead: SPC b n
"p" = "no_op"  # default: goto_prev_buffer, instead: SPC b p

[keys.normal.j]
"$" = "goto_line_end"
"0" = "goto_line_start"
"i" = "symbol_picker"
"I" = "workspace_symbol_picker"
"v" = "goto_definition"

# "Major mode"
[keys.normal.space.m]
[keys.normal.space.m.h]
"h" = "hover"
[keys.normal.space.m.g]
# TODO: Why doesn't this work?
# "g" = "goto_defintion"

# Increase/decrease numbers
[keys.normal.space.n]
"+" = "increment"
# "-" = "decrement"

# Managing projects
[keys.normal.space.p]
"b" = "buffer_picker"
"f" = "file_picker"
"h" = "file_picker"

# Searching in a project
[keys.normal.space.s]
"a" = { "p" = "global_search" }
"k" = { "p" = "global_search" }
"p" = "global_search"
"t" = { "p" = "global_search" }

# Window manipulation
[keys.normal.space.w]
"q" = "no_op"  # default: wclose, instead: d
"d" = "wclose"
"h" = "jump_view_left"  # default
"j" = "jump_view_down"  # default
"k" = "jump_view_up"  # default
"l" = "jump_view_right"  # default
"H" = "swap_view_left"  # default
"J" = "swap_view_down"  # default
"K" = "swap_view_up"  # default
"L" = "swap_view_right"  # default
"s" = "hsplit"  # default
"v" = "vsplit"  # default
"/" = "vsplit"
# TODO: Why doesn't this work?
# "-" = "hsplit"

# Text manipulation
[keys.normal.space.x]
"u" = "switch_to_lowercase"
"U" = "switch_to_uppercase"

[keys.normal.space.x.l]
"s" = ":sort"

# ---------------------------------------------------------
# Select

[keys.select]
"$" = "goto_line_end"
"0" = "goto_line_start"
"V" = "extend_line_below"
"G" = "goto_last_line"
"p" = "goto_next_paragraph"
"H" = "goto_window_top"
"L" = "goto_window_bottom"
# These do not exist in Spacemacs AFAIK:
"up" = "expand_selection"
"down" = "shrink_selection"
"left" = "select_prev_sibling"
"right" = "select_next_sibling"

[keys.select.g]
"q" = ":reflow"

# https://www.spacemacs.org/doc/DOCUMENTATION.html#executing-vim-and-emacs-exm-x-commands
[keys.select.space]
"space" = "command_palette"
"o" = "no_op"  # reserved for user in Spacemacs
